# Generated by Django 6.0.1 on 2026-04-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
